export const exampleFlow2 = {
  id: 'example-flow-2',
  title: 'Example flow 2',
  nodes: [
    {
      id: 'node1',
      name: 'node1',
      ports: {
        input: [
          {
            id: 'in-1',
            nodeId: 'node1',
            name: 'in-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
          {
            id: 'in-2',
            nodeId: 'node1',
            name: 'in-2',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
        ],
        output: [
          {
            id: 'out-1',
            nodeId: 'node1',
            name: 'out-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
          {
            id: 'out-2',
            nodeId: 'node1',
            name: 'out-2',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
        ],
      },
      metadata: {
        x: 725,
        y: 350,
        width: 200,
        height: 152.25,
      },
    },
    {
      id: 'node2',
      name: 'node2',
      ports: {
        input: [
          {
            id: 'in-1',
            nodeId: 'node1',
            name: 'in-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
          {
            id: 'in-2',
            nodeId: 'node1',
            name: 'in-2',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
        ],
        output: [
          {
            id: 'out-1',
            nodeId: 'node1',
            name: 'out-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
        ],
      },
      metadata: {
        x: 1175,
        y: 350,
        width: 200,
        height: 132.25,
      },
    },
    {
      id: 'node3',
      name: 'node3',
      ports: {
        input: [
          {
            id: 'in-1',
            nodeId: 'node1',
            name: 'in-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
        ],
        output: [
          {
            id: 'out-1',
            nodeId: 'node1',
            name: 'out-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
        ],
      },
      metadata: {
        x: 1625,
        y: 350,
        width: 200,
        height: 106.25,
      },
    },
    {
      id: 'node4',
      name: 'node4',
      ports: {
        input: [
          {
            id: 'in-1',
            nodeId: 'node1',
            name: 'in-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
          {
            id: 'in-2',
            nodeId: 'node1',
            name: 'in-2',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: ['context'],
          },
        ],
        output: [
          {
            id: 'out-1',
            nodeId: 'node1',
            name: 'out-1',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
          {
            id: 'out-2',
            nodeId: 'node1',
            name: 'out-2',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
          {
            id: 'out-3',
            nodeId: 'node1',
            name: 'out-3',
            radius: 6,
            width: 20,
            color: 'black',
            stroke: 'white',
            strokeWidth: 2,
            classes: [],
          },
        ],
      },
      metadata: {
        x: 2075,
        y: 350,
        width: 200,
        height: 172.25,
      },
    },
  ],
  links: [
    {
      id: 'e5ee9068-911d-46ef-af94-568dc4d6b42e',
      source: {
        id: 'node1',
        port: 'out-1',
      },
      target: {
        id: 'node2',
        port: 'in-1',
      },
    },
    {
      id: 'd9deacb0-ee02-475f-ae06-62a4609674ba',
      source: {
        id: 'node2',
        port: 'out-1',
      },
      target: {
        id: 'node3',
        port: 'in-1',
      },
    },
    {
      id: 'bde3b8a1-a0cb-4ed2-89b5-5a23b361060d',
      source: {
        id: 'node3',
        port: 'out-1',
      },
      target: {
        id: 'node4',
        port: 'in-1',
      },
    },
  ],
}
